"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
# import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
from nltk.corpus import stopwords
import re
import string
import pandas as pd
import numpy as np
import enchant
from nltk.tokenize import word_tokenize
import matplotlib.pyplot as plt

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rxuop9c=62%6!1@)ndmoz0--yi1uuqf4yb8p+=lyf+w67*fjc%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'singlepage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = 'images/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

try:
    read = pd.read_csv(os.path.join(BASE_DIR,'words.csv'))
    DICWORD = read['words'].tolist()
except IOError:
    text = """Pakistan’s Prime Minister Imran Khan has started a three day visit to Saudi Arabia in an effort to reset relations after tensions between the longtime allies in recent years.

    Khan’s arrival in Riyadh on Friday after an invitation from Saudi Crown Prince Mohammed bin Salman holds much significance, analysts say. While Pakistan and Saudi Arabia have historically been close allies, their strong ties have suffered several setbacks.The covid-19 virus came to human knowledge when it was first discovered in Wuhan city in China, since then it has rapidly spread and soon it formed itself into a pandemic on 11 March 2020. Though Covid-19 is considered as novel virus but still it gave devastating effects on humanity. This virus is boundaryless and has spread all over the world and no nation is immune to the virus. Coronavirus has impacted the world in a very fast manner. Just in few weeks, it has dramatically changed the lifestyle of humans and billions of people are forced to stay at home, self-isolating themselves and work and learn from the home. It has not only limited the freedom of humans but also initiated full lockdowns in many countries. As of now, the virus has infected 114 million people around the world and also has caused deaths of more than 2 million people including children, adults and elderly destroying the health management system of almost every single country. Number of deaths were reaching almost 6000 per day and there was no immediate solution. The virus was not showing any sign of slowing down and was rapidly spreading around the globe. Many peoples lost their jobs, making them unable to pay for their daily needs. Forcing the governments to take actions to overcome these problems like Prime minister of Pakistan “Imran khan” launched Ehsaas emergency cash program in which one-time cash grant of 12,000 PKR have been distributed among the ones who are daily earners and are unable to pay for their daily needs. In addition to that, loan programs were created with lower interest rates to support businesses. In this way, relief was provided by the governments to citizens and businesses. Coronavirus does not only affect the health systems but it has also created obstacles for the education system all over the globe. The pandemic-initiated lockdowns which caused the closure of educational institutions around the globe so that students can practice social distancing measures.
    E-learning can be proved very effective in developed countries but underdeveloped Asian countries were facing more obstacles than the western countries which are developed because of limited resources available to them. The education system in these underdeveloped countries was not prepared for such circumstances which led them to more gaps in education. Including health system, education sector was also one of the worst hits by coronavirus pandemic. Since coronavirus was giving a very hard time to the education sector, online learning seems to be the only solution. And to implement those two kinds of tools are needed as stated by Oranburg. First, the hardware equipment which includes a computer, microphone, camera, and a good internet network. The second tool includes online learning applications such as zoom, Microsoft Teams, etc. These types of software allow users to hold virtual meetings without having to move to the same location but as these software does not come cheap, can education institution in countries like Pakistan afford it? Indeed, this can be taken as opportunity for the teachers and student to use the technology in order to improve the quality of the education. But in underdeveloped countries where technology inequality is very high, is online learning reliable or not? This study was conducted to highlight the effects of corona virus on higher education, obstacles faced by student during these challenging times and also to provide a reliable prototype which can be used as a medium for online learning. This paper is going to address the situation faced by higher education students during corona virus pandemic.He was accompanied by federal ministers Asad Umar, Shah Mahmood Qureshi, Fawad Chaudhry, Hammad Azhar and others. The premier arrived in Moscow Wednesday on a two-day official visit at the invitation of Russian President Vladimir Putin.

    The visit comes at a time when Russia and Ukraine are engaged in a military conflict.Hearing the plea of a citizen named Farooq, Justice Shahid Karim ordered hefty fines over the persons involved in encroachment in the province.

    The LHC also ordered action against the shopkeepers for giving the footpaths of their shops on rent that ultimately causes encroachments. The bench has also sought details of under construction plazas in Lahore. 122 units were found operating without protective measures and 170 were sealed over discharging too much smoke.

    Meanwhile, the Ministry of Climate Change has established a smog control room in Lahore to ensure regular monitoring of smog that causes health hazards to people in different areas of the province.

    Special Assistant to the Prime Minister (SAPM) on Climate Change Malik Amin Aslam had said the process to combat smog had begun. Taking to Twitter to respond to the court’s decision, the information minister said that the police and prosecution played their responsibility in the Noor Mukadam case and the court decided the matter within four months.

    “This is the justice that people of Pakistan expect,” Fawad Chaudhry said and added, “We hope that institutions responsible for providing justice will fulfil expectations from them and rule of law will prevail. Offer orders for the candidates passing the Sukkur IBA test are ready and will be disbursed today. The Sindh Education department will distribute 50,000 offer orders to the students.

    Sindh Minister for Education and Culture, Syed Sardar Ali Shah will give away offer orders to the successful candidates in Lyari’s Government School today.The minister said that it was a big achievement of the Pakistan People’s Party (PPP), which has provided fifty thousand teaching jobs on merit.

    In October last, the Sindh cabinet approved the proposal of easing the recruitment policy for the teachers after only a fewer number of candidates were able to clear the test conducted by IBA Sukkur for over 40,000. According to the ISPR, during the meeting, matters of mutual interest, regional security situation and bilateral cooperation between the two countries were discussed.

    COAS Qamar Javed Bajwa said that Pakistan values its relations with Uzbekistan, particularly defence cooperation. Both reiterated the desire to further enhance bilateral relations including efforts for peace and security in the region. Uzbekistan’s Ambassador Aybek Arif Usmanov appreciated Pakistan’s role in regional stability and pledged to keep working for better relations between two brotherly countries.

    Recently, Chief of Army Staff (COAS) General Qamar Javed Bajwa has paid an official visit to Belgium, the Inter-Services Public Relations (ISPR) said.

    During the visit, COAS Bajwa called on Secretary-General of the European External Action Services (EEAS) Stefano Sannino and the Chairman of the EU Military Committee General Claudio Graziano.

    During the meeting matters of mutual interest, overall regional security situation including current situation in Afghanistan and bilateral relations with EU were discussed.

    The army chief said that Pakistan values its relations with EU countries and earnestly look forward to enhance mutual cooperation based on common interests, according to the ISPR.

    EU dignitaries appreciated Pakistan’s sincere efforts for peace and stability in the region and pledged to play their role for increased collaboration with Pakistan at all leve. ls. While hearing petitions filed against Federal Investigation Agency (FIA) for exceeding from its authorities, the CJ IHC Justice Athar Minallah remarked, “You are doing self-censorship through this law.”

    The CJ said that whenever an ordinance is prepared, it has to get the green signal from both the Houses over which, Attorney General said that the approval can be taken from even one House. Later, the IHC extended the stay order on section 20 of the PECA Amendment Bill 2022 and stopped the authorities from carrying out arrests.

    The court remarked that the director-general of the Federal Investigation Agency (FIA) will be responsible if detentions will be made under section 20.

    The next hearing on the case will be held on March 10.
    Earlier in the day, Chief Justice (CJ) Islamabad High Court (IHC), Justice Athar Minallah said he will not entertain pleas of political parties against the Prevention of Electronic Crimes Act (PECA) ordinance.

    “I will not entertain pleas of political parties against the PECA ordinance,” Justice Athar Minallah was quoted as saying.  He advised political parties to use the forum of the Parliament against the law. The prime minister who was accompanied by federal ministers Asad Umar, Shah Mahmood Qureshi, Fawad Chaudhry and others, visited the monument of heroes killed in World War II and a laid floral wreath. 
    During his meeting with President Vladimir Putin, Prime Minister Khan will exchange views on international and regional issues. They will also discuss bilateral relations, especially cooperation in the energy sector.

    Matters pertaining to Islamophobia and situation in Afghanistan will also come under discussion. Besides, the Prime Minister will visit the biggest mosque of Russia and Islamic Centre in Moscow. Prime Imran Khan’s visit will strengthen bilateral relations between Pakistan and Russia. The father and son duo and other accused appeared before the court. In the Ashiana-e-Iqbal case, the accountability court recorded statements of three prosecution witnesses who were also cross-examined by defence lawyers. The court directed the National Accountability Bureau (NAB) to present more witnesses in the case on next date of hearing.

    While hearing the Ramaza Sugar Mills case, the court directed the anti-corruption watchdog to furnish its arguments on an application of Hamza seeking his acquittal. Both cases were later adjourned till March 4.

    Speaking to the media, opposition leader in the National Assembly and PML-N President Shehbaz said the incumbent government has destroyed the country’s economy. Taking aim at PTI leaders, he said they have made the political environment toxic by labeling opposition leaders “thieves and robbers”. Speaking to the media following the pronouncement of the judgement, Shaukat Mukadam said, “an exemplary punishment has been handed to the prime accused. “It was a question of all of Pakistan’s daughters. I hoped that I will get justice and I got it,” Noor Mukadam Father added, thanking the media for keeping the matter “alive”. He said everyone was praying for justice. “The entire nation and world were with us,” he said. Additional District and Sessions Judge Justice Atta Rabbani announced the verdict. The prime accused, Zahir Jaffer, was sentenced to death. Besides Zahir, the court handed ten-year imprisonment to two of his employees — Jamil and Jan Mohammad — while acquitted Tahir Zahoor, the owner of a counselling and psychotherapy service named Therapy Works, and his five employees."""
    text = re.sub(r'[^\w\s]','',text)
    stop_words = set(stopwords.words('english'))
    word_tokens = word_tokenize(text)
    text = [w for w in word_tokens if not w.lower() in stop_words]
    text = []
    for w in word_tokens:
        if w not in stop_words:
            text.append(w)
    d = enchant.Dict("en_US")
    a = [x for x in text if not d.check(x)]
    a.append("unavailability")
    dic = {'words':a}
    df = pd.DataFrame(dic) 
    df.to_csv('words.csv', index=False)
    read = pd.read_csv(os.path.join(BASE_DIR,'words.csv'))
    DICWORD = read['words'].tolist()


data = pd.read_csv(os.path.join(BASE_DIR,'twitter.csv'))
data["labels"] = data["class"].map({0: "Hate Speech", 1: "Offensive Language", 2: "No Hate and Offensive"})
data = data[["tweet", "labels"]]
stemmer = nltk.SnowballStemmer("english")
stopword = set(stopwords.words('english'))

def clean(text):
    stemmer = nltk.SnowballStemmer("english")
    stopword = set(stopwords.words('english'))
    text = str(text).lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    text = [word for word in text.split(' ') if word not in stopword]
    text=" ".join(text)
    text = [stemmer.stem(word) for word in text.split(' ')]
    text=" ".join(text)
    return text

data["tweet"] = data["tweet"].apply(clean)

x = np.array(data["tweet"])
y = np.array(data["labels"])

CV = CountVectorizer()
X = CV.fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

CLF = DecisionTreeClassifier()
CLF.fit(X_train,y_train)
CLF.score(X_test,y_test)